language: ruby
before_script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then gem install jekyll; fi' 
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then gem install percy-cli; fi' 
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then jekyll build; fi' 
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then percy snapshot ./; fi' 


notifications:
  email:
    recipients:
      - mplaisted@businessink.com
    on_success: always
